# runtime: python27
# api_version: 1
# threadsafe: true
# handlers:
# - url: /
#   static_files: public/index.html
#   upload: public/index.html

# - url: /(.*)
#   static_files: public/\1
#   upload: public/(.*)
runtime: nodejs10
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
